Repository godotengine/godot, pull requests merged in 2018-03, with the labels that each got.

#17135 Fix server build on FreeBSD
  platform/server/detect.py
  platform/server/platform_config.h
  platform/x11/crash_handler_x11.cpp
Labels: bug, topic:buildsystem

#17137 Fix intermittent audio driver crash during startup on Android
  platform/android/audio_driver_opensl.cpp
Labels: bug, platform:android, topic:audio

#17058 Fixed Windows ignoring minimized/maximized status set by user
  platform/windows/os_windows.cpp
Labels: bug, cherrypick, topic:core

#17133 [Build] Fix WebM (libvpx) SIMD optimizations on macOS.
  platform/osx/detect.py
Labels: bug, topic:core, topic:rendering

#17140 Viewport: Fix missing tooltips w/ disabled physics object picking
  scene/main/viewport.cpp
Labels: bug, cherrypick, topic:core

#17142 Remove unneeded and problematic minilex.c from lws.
  modules/websocket/SCsub
  thirdparty/README.md
  thirdparty/lws/minilex.c
Labels: bug, topic:thirdparty

#17143 fix accidental SConstruct reverts
  SConstruct
Labels: bug, topic:buildsystem

#17145 Fix regression through fa98637acaab9135568bf0d43a65c9c96b59c32d
  scene/gui/rich_text_label.cpp
Labels: bug, cherrypick, topic:core

#17129 Allow degenerate triangles in polygon triangulation when necessary.
  core/math/triangulate.cpp
  core/math/triangulate.h
Labels: bug, cherrypick, topic:core

#17152 2to3 exporter: Add a hack to convert rotation values in Animation tracks
  editor/editor_export_godot3.cpp
Labels: bug, topic:editor

#17156 2to3 exporter: Fix NodePath prop remaps in .scn
  editor/editor_export_godot3.cpp
Labels: bug, topic:editor

#17164 [DOCS] Small fix to PinJoint2D
  doc/classes/PinJoint2D.xml
Labels: documentation, enhancement

#17163 [DOCS] NetworkedMultiplayerENet
  modules/enet/doc_classes/NetworkedMultiplayerENet.xml
Labels: documentation, enhancement

#17167 GridMap: fix next/prev plane text, fix meta not found
  modules/gridmap/grid_map_editor_plugin.cpp
Labels: bug, topic:editor

#17168 Prune cache at the beginning and end of build (master)
  SConstruct
Labels: enhancement, topic:buildsystem

#17170 Prune cache at the beginning and end of build (2.1)
  SConstruct
Labels: enhancement, topic:buildsystem

#17171 Don't crash when trying to add an invalid navmesh
  scene/3d/navigation.cpp
Labels: cherrypick, topic:core, usability

#17175 [GLES2] Adds GLES2 renderer support on macOS.
  drivers/gles2/rasterizer_gles2.cpp
  platform/osx/os_osx.h
  platform/osx/os_osx.mm
  thirdparty/glad/glad.c
  thirdparty/glad/glad/glad.h
Labels: enhancement, platform:osx, topic:rendering

#17173 fix GLES2 line rendering
  drivers/gles2/rasterizer_canvas_gles2.cpp
Labels: bug, topic:rendering

#17178 Fix serialization of identifiers with non printable ASCII characters
  scene/resources/scene_format_text.cpp
Labels: bug, cherrypick, topic:core

#17177 Fix serialization of identifiers with non printable ASCII characters
  editor/editor_export_godot3.cpp
  scene/resources/scene_format_text.cpp
Labels: bug, topic:core

#17185 s/Camear/Camera in docs
  doc/classes/Camera.xml
Labels: bug, documentation

#17158 [GLES2] Renderer selection improvement
  main/main.cpp
  platform/osx/os_osx.mm
  platform/x11/os_x11.cpp
  platform/x11/os_x11.h
Labels: bug, enhancement, topic:rendering

#17192 Fix more regressions in RichTextLabel from PR 15711
  scene/gui/rich_text_label.cpp
Labels: bug, cherrypick, topic:core

#17219 [DOCS] Small fix to Area: Fix copy/paste errors
  doc/classes/Area.xml
Labels: bug, documentation

#17187 [macOS] Hack to force window activation for non-bundled app.
  platform/osx/os_osx.mm
Labels: cherrypick, enhancement, platform:osx, topic:porting

#17225 Fix floatBitsToUint shader builtin function
  servers/visual/shader_language.cpp
Labels: bug, cherrypick, topic:core, topic:rendering

#17035 Fix memory leaks
  thirdparty/README.md
  thirdparty/b2d_convexdecomp/b2Polygon.cpp
  thirdparty/etc2comp/EtcFilter.cpp
  thirdparty/libsimplewebm/libwebm/mkvparser/mkvparser.cc
Labels: bug, topic:thirdparty

#17226 Modify OSX can_export logic to match the logic from EditorExportPlatformPC::can_export
  platform/osx/export/export.cpp
Labels: enhancement, topic:editor

#17236 Fix for a possible crash when a custom theme is not loaded properly
  editor/editor_themes.cpp
Labels: bug, cherrypick, topic:core

#17262 Fix uninitialized data in Sprite::_get_rects()
  scene/2d/sprite.cpp
Labels: bug, topic:core

#17256 Clean and expose get_audio/video_driver_* funcs on OS class
  core/bind/core_bind.cpp
  core/bind/core_bind.h
  core/os/os.cpp
  core/os/os.h
  drivers/unix/os_unix.cpp
  drivers/unix/os_unix.h
  platform/android/os_android.cpp
  platform/iphone/os_iphone.cpp
  platform/javascript/os_javascript.cpp
  platform/osx/os_osx.h
  platform/osx/os_osx.mm
  platform/windows/os_windows.cpp
  platform/windows/os_windows.h
  platform/x11/os_x11.cpp
  platform/x11/os_x11.h
Labels: enhancement, topic:core

#17266 Fix new Node dialog Create button behavior
  editor/create_dialog.cpp
Labels: enhancement, topic:editor, usability

#17249 skip demo download prompt if ssl is unavailable
  editor/project_manager.cpp
Labels: cherrypick, enhancement, topic:editor

#17285 Add OpenGL extension support checks (Debug/FBO) and FBO fallback for GLES2
  drivers/gles2/rasterizer_gles2.cpp
  drivers/gles3/rasterizer_gles3.cpp
  thirdparty/glad/glad.c
  thirdparty/glad/glad/glad.h
Labels: enhancement, topic:rendering

#17247 In CanvasItemEditor, prioritize selected items when dragging
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: enhancement, topic:editor

#17195 Generate mouse events from touch on X11 (2.1)
  platform/x11/os_x11.cpp
  platform/x11/os_x11.h
Labels: enhancement, platform:linuxbsd, topic:porting

#17205 FIX Windows enter/exit mouse notifications
  scene/main/scene_tree.cpp
Labels: bug, cherrypick, topic:core

#17206 Backport FIX mouse notifications missings ->godot2
  scene/main/scene_main_loop.cpp
Labels: bug, topic:core

#17304 [GL] Explicitly set OpenGL 3.3 profile to Core (X11, Windows) and enable GLES2 on Windows.
  platform/windows/context_gl_win.cpp
  platform/windows/os_windows.cpp
  platform/x11/context_gl_x11.cpp
Labels: enhancement, platform:linuxbsd, platform:windows, topic:rendering

#17315 Change shebang of pre-commit-clang-format hook to make it portable
  misc/hooks/pre-commit-clang-format
Labels: enhancement

#17317 Disable FreeType SIMD in HTML5 builds
  modules/freetype/SCsub
Labels: bug, platform:html5, topic:buildsystem, topic:porting, topic:thirdparty

#17318 Fix silent failure of importing OGG Vorbis files
  modules/stb_vorbis/resource_importer_ogg_vorbis.cpp
Labels: enhancement, topic:editor

#17243 Fix being able to create folder name with ending '.' on Windows
  editor/filesystem_dock.cpp
Labels: enhancement, platform:windows, topic:editor

#17343 Reinstate WebGL 1.0 (GLES2) driver in HTML5 platform
  core/os/os.h
  platform/javascript/os_javascript.cpp
Labels: enhancement, platform:html5, topic:porting, topic:rendering

#17340 Prevent division by zero in GridContainer
  scene/gui/grid_container.cpp
Labels: bug, cherrypick, topic:core

#17189 Fixes Selection of Sprites using AtlasTexture
  scene/2d/sprite.cpp
Labels: bug, cherrypick, enhancement, topic:editor

#17341 Fix unselectable flipped sprites (fixes 16461)
  scene/2d/sprite.cpp
Labels: bug, topic:editor

#16485 Bring back Vector2.cross()
  core/math/math_2d.cpp
  core/math/math_2d.h
  core/variant_call.cpp
  doc/classes/Vector2.xml
  servers/physics_2d/joints_2d_sw.cpp
Labels: enhancement, topic:core

#17354 Make the shader token names consistent.
  servers/visual/shader_language.cpp
Labels: bug, topic:core, topic:rendering

#17347 FIX to broken item select list (zoom and RMB)
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, cherrypick, topic:editor

#17378 Update libwebm
  modules/webm/SCsub
  thirdparty/libsimplewebm/libwebm/README.libvpx
  thirdparty/libsimplewebm/libwebm/common/webmids.h
  thirdparty/libsimplewebm/libwebm/mkvparser/mkvparser.cc
  thirdparty/libsimplewebm/libwebm/mkvparser/mkvparser.h
Labels: enhancement, topic:thirdparty

#17473 Fixed several leaks
  drivers/gles3/rasterizer_gles3.cpp
  drivers/gles3/rasterizer_scene_gles3.cpp
  drivers/gles3/rasterizer_scene_gles3.h
  servers/visual/visual_server_raster.cpp
  servers/visual/visual_server_scene.cpp
Labels: bug, topic:rendering

#17474 Fix non working action names containing whitespaces
  core/project_settings.cpp
  editor/project_settings_editor.cpp
Labels: bug, topic:core, topic:editor

#17399 [DOCS] Update Image format enumeration documentation
  doc/classes/Image.xml
Labels: documentation

#17402 Fix invalid mix function overload
  servers/visual/shader_language.cpp
Labels: bug, cherrypick, topic:core

#17416 Avoid confusing traceback on attempting build without platform option
  SConstruct
Labels: enhancement, topic:buildsystem

#17426 expose Itemlist.is_anything_selected
  scene/gui/item_list.cpp
Labels: enhancement, topic:core

#17432 Update TileMap when its TileSet changes
  scene/2d/tile_map.cpp
  scene/2d/tile_map.h
Labels: bug, topic:editor

#17442 EditorNode: fix clicking ok keeps trying to save
  editor/editor_node.cpp
Labels: bug, topic:editor

#17455 ScriptTextEditor: fix capitalize offset
  editor/plugins/script_text_editor.cpp
Labels: bug, topic:editor

#17191 Fix infinite loop in GridContainer layout
  scene/gui/grid_container.cpp
Labels: bug, cherrypick, topic:editor

#17410 Fixes infinite loop in GridContainer
  scene/gui/grid_container.cpp
Labels: bug, cherrypick, topic:core

#17482 fix iOS build - error due to GLES2 missing include
  platform/iphone/platform_config.h
Labels: bug, platform:ios, topic:buildsystem

#17319 Build polygon clipper only in tools builds
  core/SCsub
  editor/SCsub
Labels: bug, cherrypick, platform:html5, topic:buildsystem, topic:porting, topic:thirdparty

#17454 Fixes importing hdr files with extra header info
  modules/hdr/image_loader_hdr.cpp
Labels: enhancement, topic:core

#17441 Fix column width on AutoLoad table on hidpi displays
  editor/editor_autoload_settings.cpp
Labels: bug, topic:editor, usability

#17435 Show error icon at "Output" in case of errors
  editor/editor_log.cpp
  editor/editor_log.h
  editor/editor_node.cpp
Labels: enhancement, topic:editor

#17422 Implement line clipping for `TextureProgress` to avoid bad rendering
  scene/gui/texture_progress.cpp
Labels: bug, topic:core

#17413 Update preview on filesystem change
  editor/editor_file_system.cpp
Labels: enhancement, topic:editor

#17406 Fix broken hover/select coloring of keys in animation editor
  editor/animation_editor.cpp
  editor/icons/icon_key_selected.svg
  editor/icons/icon_key_valid.svg
Labels: bug, topic:editor

#17404 Fix wrong pan direction in animation player ui
  editor/animation_editor.cpp
Labels: cherrypick, enhancement, topic:editor

#17390 Fixes overlapping text labels in animation editor timeline
  editor/animation_editor.cpp
Labels: bug, topic:editor

#17383 Better tab support for color picker
  scene/gui/color_picker.cpp
  scene/gui/color_picker.h
Labels: enhancement, topic:core

#17440 Properly closing all files in Python build code
  core/SCsub
  core/make_binders.py
  doc/tools/makemd.py
  doc/tools/makerst.py
  editor/SCsub
  editor/icons/SCsub
  editor/translations/extract.py
  main/SCsub
  methods.py
  misc/scripts/fix_headers.py
  misc/scripts/make_glwrapper.py
  platform/SCsub
  platform/android/SCsub
Labels: enhancement, topic:buildsystem

#17381 AnimationPlayer: fix scrubbing after play backwards
  editor/plugins/animation_player_editor_plugin.cpp
  scene/animation/animation_player.cpp
Labels: bug, topic:core, topic:editor

#17380 Fix overwriting all common properties when using `Change Type` tool
  editor/scene_tree_dock.cpp
Labels: bug, topic:core

#17379 AnimationPlayer: fix popups close on double click
  editor/animation_editor.cpp
Labels: bug, cherrypick, topic:editor

#17359 Auto completion edge jump
  scene/gui/text_edit.cpp
Labels: enhancement, topic:editor, usability

#17314 Fix bad autocomplete of partially written node paths when using syntactic sugar notation ($)
  scene/gui/text_edit.cpp
Labels: bug, topic:editor, usability

#17311 Improved error checking at EditorExportPlatformPC::export_project
  core/os/dir_access.cpp
  editor/editor_export.cpp
  platform/osx/export/export.cpp
Labels: cherrypick, enhancement, topic:editor

#17257 Fix garbage in string padding.
  core/io/marshalls.cpp
Labels: bug, cherrypick, topic:core

#17255 fix enum from preloaded script in export
  modules/gdscript/gdscript_parser.cpp
Labels: bug, topic:gdscript

#17254 Update wrap functions
  core/math/math_funcs.cpp
  core/math/math_funcs.h
Labels: enhancement, topic:core

#17184 TileSetEditorPlgn: use EditorHandle icon as handle
  editor/plugins/tile_set_editor_plugin.cpp
  editor/plugins/tile_set_editor_plugin.h
Labels: cherrypick, enhancement, topic:editor

#17176 EditorAudioBus: expand effects list
  editor/editor_audio_buses.cpp
Labels: cherrypick, enhancement, topic:editor, usability

#17172 Add "Show Origin" and "Show Viewport" options to 2D Editor Viewport
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.h
Labels: cherrypick, enhancement, topic:editor

#17166 TileSet&TextureRegion: fix error when getting nonexistent tile
  editor/plugins/texture_region_editor_plugin.cpp
  editor/plugins/tile_set_editor_plugin.cpp
Labels: bug, cherrypick, topic:editor

#17154 ScriptEditor: Use EditorSettings instead of hardcoded values in constructor.
  editor/plugins/script_editor_plugin.cpp
Labels: bug, cherrypick, topic:editor

#17141 Support for uneven amount of channels on PulseAudio
  drivers/pulseaudio/audio_driver_pulseaudio.cpp
  drivers/pulseaudio/audio_driver_pulseaudio.h
Labels: bug, platform:linuxbsd, topic:audio

#17138 Make md5's not be in the same file as the import settings
  editor/editor_file_system.cpp
Labels: enhancement, topic:editor

#17116 Fix round preview getting square on "run scene" (issue 16734)
  editor/editor_node.cpp
  editor/plugins/editor_preview_plugins.cpp
  editor/plugins/editor_preview_plugins.h
Labels: bug, cherrypick, topic:editor

#17114 Fix line thickness for CollisionPolygon2D.
  scene/2d/collision_polygon_2d.cpp
Labels: bug, cherrypick, topic:editor

#17104 More threading in AssetLib
  editor/plugins/asset_library_editor_plugin.cpp
Labels: cherrypick, enhancement, topic:assetlib

#17094 Add an hinting mode setting to DynamicFonts
  doc/classes/DynamicFontData.xml
  editor/editor_fonts.cpp
  editor/editor_settings.cpp
  scene/resources/dynamic_font.cpp
  scene/resources/dynamic_font.h
Labels: cherrypick, enhancement, topic:core, topic:editor

#17079 GridMapEditorPlgn: fix a leak
  modules/gridmap/grid_map_editor_plugin.cpp
Labels: bug, cherrypick, topic:editor

#17040 Deprecated Godot 3D physics engine
  servers/register_server_types.cpp
Labels: enhancement, topic:physics

#17013 Update icons when theme changed
  editor/editor_about.cpp
  editor/editor_audio_buses.cpp
  editor/editor_node.cpp
  editor/editor_node.h
  editor/plugins/asset_library_editor_plugin.cpp
  editor/plugins/asset_library_editor_plugin.h
  editor/plugins/item_list_editor_plugin.cpp
  editor/plugins/texture_region_editor_plugin.cpp
  editor/plugins/tile_map_editor_plugin.cpp
  editor/plugins/tile_set_editor_plugin.cpp
  editor/project_export.cpp
  editor/project_settings_editor.cpp
  editor/scene_tree_editor.cpp
  editor/script_create_dialog.cpp
  editor/script_create_dialog.h
  editor/script_editor_debugger.cpp
Labels: bug, topic:editor

#16978 Add icon to TileMapEditor popupmenu
  editor/plugins/tile_map_editor_plugin.cpp
Labels: enhancement, topic:editor

#16971 TileMap: add fix_invalid_tiles
  doc/classes/TileMap.xml
  editor/plugins/tile_map_editor_plugin.cpp
  editor/plugins/tile_map_editor_plugin.h
  scene/2d/tile_map.cpp
  scene/2d/tile_map.h
Labels: enhancement, topic:core, topic:editor

#16895 Fix get_drive (bookmarks) in linux not working
  drivers/unix/dir_access_unix.cpp
Labels: bug, cherrypick, platform:linuxbsd, topic:core

#17485 [DOCS] Net.MultiplayerEnet: List returned errors
  modules/enet/doc_classes/NetworkedMultiplayerENet.xml
Labels: cherrypick, documentation, enhancement

#17235 [Mono] change function names to PascalCase and set abstract classes as abstract
  modules/mono/editor/bindings_generator.cpp
  modules/mono/glue/cs_files/StringExtensions.cs
  modules/mono/glue/cs_files/Transform.cs
  modules/mono/glue/cs_files/VERSION.txt
Labels: enhancement, topic:mono

#17488 expose itemlist.unselect_all()
  scene/gui/item_list.cpp
Labels: enhancement, topic:core

#17486 Fix a potential bug hinted by clang
  core/variant_op.cpp
Labels: bug, discussion, topic:core

#17345 expose Itemlist.move_item and optimize functionality
  scene/gui/item_list.cpp
  scene/gui/item_list.h
Labels: enhancement, topic:core

#17420 Added error checks for fscache saving
  editor/editor_file_system.cpp
  editor/editor_settings.cpp
Labels: bug, topic:editor

#17489 [DOCS] Input
  doc/classes/Input.xml
Labels: documentation, enhancement

#17493 Fixed leak in BulletPhysicsServer
  modules/bullet/bullet_physics_server.cpp
Labels: bug, cherrypick, topic:physics

#17506 SCons: Fix running 'scons' without platform argument
  SConstruct
Labels: bug, cherrypick, topic:buildsystem

#17194 Enable SCons to autodetect Windows MSVC compiler
  SConstruct
  platform/uwp/detect.py
  platform/windows/detect.py
Labels: enhancement, platform:windows, topic:buildsystem

#17520 Check only for WebGL 1.0 before starting downloads, move test to HTML file
  misc/dist/html/default.html
  platform/javascript/engine.js
  platform/javascript/os_javascript.cpp
Labels: enhancement, platform:html5, topic:porting

#17528 Added missing import BoolVariable
  platform/uwp/detect.py
  platform/windows/detect.py
Labels: bug, platform:uwp, topic:buildsystem

#17529 Fix script template on `_ready` behavior
  modules/gdscript/gdscript_editor.cpp
Labels: bug, topic:gdscript

#17536 Fix MinGW cross-build
  platform/windows/detect.py
Labels: bug, platform:windows, topic:buildsystem

#17388 Mono: Avoid invalid class names.
  core/script_language.h
  editor/script_create_dialog.cpp
  modules/mono/csharp_script.cpp
  modules/mono/csharp_script.h
Labels: enhancement, topic:editor, topic:mono, usability

#17541 [DOCS] Node: Networking updates, fix outdated and missing docs
  doc/classes/Node.xml
Labels: cherrypick, documentation, enhancement

#17533 Hinted shader uniforms can have a default value
  servers/visual/shader_language.cpp
Labels: bug, topic:core, topic:rendering

#17527 Fix debugger_stdout_settings being ignored
  main/main.cpp
Labels: bug, topic:core

#17514 Add brief description
  doc/classes/Navigation2D.xml
Labels: documentation, enhancement

#17407 Fix mismatch between Color.h and Color.from_hsv()
  core/color.cpp
Labels: bug, discussion, topic:core

#17376 Added File.get_path and File.get_path_absolute functions
  core/bind/core_bind.cpp
  core/bind/core_bind.h
  core/os/file_access.h
  doc/classes/File.xml
  drivers/unix/file_access_unix.cpp
  drivers/unix/file_access_unix.h
  drivers/windows/file_access_windows.cpp
  drivers/windows/file_access_windows.h
Labels: cherrypick, enhancement, topic:core

#17296 Generate controller mapping class from one or more SDL2 database files
  main/SCsub
  main/default_controller_mappings.h
  main/gamecontrollerdb.txt
  main/gamecontrollerdb_204.txt
  main/gamecontrollerdb_205.txt
  main/godotcontrollerdb.txt
  main/input_default.cpp
Labels: enhancement, topic:buildsystem

#17237 Fix wrong SSL handshake
  core/io/http_client.cpp
Labels: bug, cherrypick, topic:network

#17293 Fix "ui_accept" action not calling _pressed() function in GDScript Button
  scene/gui/base_button.cpp
Labels: bug, cherrypick, topic:core

#17291 completed-signal for coroutines with more than one yield
  modules/gdscript/gdscript_function.cpp
  modules/gdscript/gdscript_function.h
Labels: bug, cherrypick, topic:gdscript

#17264 Fix gesture events being blocked
  scene/main/viewport.cpp
Labels: bug, topic:core

#17248 Apply culling margin (fixes issue #16115)
  servers/visual/visual_server_scene.cpp
Labels: bug, topic:rendering

#17130 Fix polyline rendering when width <= 1.
  drivers/gles3/rasterizer_canvas_gles3.cpp
Labels: bug, cherrypick, topic:rendering

#16964 AudioServer emit bus_layout_changed signal when adding, moving or del…
  servers/audio_server.cpp
Labels: cherrypick, enhancement, topic:audio

#17537 InterpolatedCamera: use internal_process
  scene/3d/interpolated_camera.cpp
Labels: enhancement, topic:core

#16947 GUI elements ui_action usage, improvements
  core/input_map.cpp
  core/project_settings.cpp
  scene/gui/line_edit.cpp
  scene/gui/option_button.cpp
  scene/gui/option_button.h
  scene/gui/popup_menu.cpp
  scene/gui/scroll_bar.cpp
  scene/gui/slider.cpp
  scene/gui/tree.cpp
  scene/gui/tree.h
  scene/main/viewport.cpp
Labels: enhancement, topic:core

#17179 [mono] add the 'Facades' subfolder to the searched directories
  modules/mono/mono_gd/gd_mono_assembly.cpp
Labels: bug, topic:mono

#17564 Open textfile in textmode
  main/SCsub
Labels: bug, topic:buildsystem

#17590 Fixed small typo in the "InstancePlaceholder" doc
  doc/classes/InstancePlaceholder.xml
Labels: bug, documentation

#17619 Mono: Runtime main args and assembly search fixes
  modules/mono/mono_gd/gd_mono.cpp
  modules/mono/mono_gd/gd_mono_assembly.cpp
Labels: bug, cherrypick, topic:mono

#17606 Improve Input.is_action_just_* docs.
  doc/classes/Input.xml
Labels: documentation, enhancement

#17617 Disable Emscripten assertions in release_debug builds
  platform/javascript/detect.py
Labels: cherrypick, enhancement, platform:html5, topic:buildsystem

#17616 2.1 HTML5 fixes
  misc/dist/html/default.html
  misc/dist/html_fs/godotfs.js
  platform/javascript/audio_server_javascript.cpp
  platform/javascript/detect.py
  platform/javascript/javascript_main.cpp
  platform/javascript/os_javascript.cpp
Labels: bug, platform:html5, topic:porting

#17603 Fix Mono builds with Python 3.
  modules/mono/config.py
Labels: bug, topic:buildsystem

#17618 Fixes wrong calculation of gridcontainer's children size
  scene/gui/grid_container.cpp
Labels: bug, cherrypick, topic:core

#17548 Fixes scrollbars in Canvas Item Editor
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.h
Labels: bug, topic:editor

#17622 A couple of fixes for glTF importing
  editor/import/editor_scene_importer_gltf.cpp
Labels: bug, cherrypick, topic:editor

#17560 2 to 3 converter: More fixes to the property renames
  editor/editor_export_godot3.cpp
Labels: bug, enhancement, topic:editor

#17634 Fix mono build properly!
  modules/mono/config.py
Labels: bug, topic:buildsystem, topic:mono

#17629 [macOS] Implement OS_OSX::execute (using NSTask)
  platform/osx/os_osx.h
  platform/osx/os_osx.mm
Labels: bug, platform:osx, topic:porting

#17632 Fix oversampled font artifacts after resize
  scene/main/scene_tree.cpp
Labels: bug, topic:core

#17589 Fix saving unmodified scenes and resources
  editor/editor_node.cpp
Labels: bug, topic:editor, usability

#17637 Fix crash in `canvas_item_add_polyline` when passing more points than colors
  servers/visual/visual_server_canvas.cpp
Labels: bug, topic:core

#17645 Fix getting Android device information
  platform/android/export/export.cpp
Labels: bug, cherrypick, topic:editor
