Repository godotengine/godot, pull requests merged in 2019-12, with the labels that each got.

#33640 Fix HTTP HEAD requests
  core/io/http_client.cpp
  core/io/http_client.h
Labels: bug, topic:network

#34019 Update transform property in the inspector when changing translation/rotation/scale
  scene/3d/spatial.cpp
Labels: enhancement, topic:editor

#33997 makerst: Escape default values using reST markup
  doc/tools/makerst.py
  modules/gridmap/doc_classes/GridMap.xml
Labels: documentation, enhancement

#34002 Don't try to initialize empty NativeLibrary
  modules/gdnative/nativescript/nativescript.cpp
Labels: bug, crash, topic:editor, topic:gdnative

#33994 Flush remaining messages before quitting the game when loading fails
  main/main.cpp
Labels: bug, topic:core

#34043 Fixed LineEdit text removal and placeholder caret alignment
  scene/gui/line_edit.cpp
  scene/gui/line_edit.h
Labels: bug, topic:core

#34022 Fixed errors in AnimationPlayerEditor when switching current_animation in the inspector
  editor/plugins/animation_player_editor_plugin.cpp
Labels: bug, topic:editor

#34042 Add missing on error manifest struct destroy in pluginscript script init
  modules/gdnative/pluginscript/pluginscript_script.cpp
Labels: bug, topic:gdnative, topic:plugin

#34047 Properly remove joint when a physical bone is removed from the scene
  scene/3d/physics_body.cpp
Labels: bug, topic:physics

#34048 Center Script Editor when jumping to bookmarks/breakpoints
  editor/code_editor.cpp
  editor/plugins/script_text_editor.cpp
Labels: enhancement, topic:editor, usability

#33985 Disable shadow map sampling when shadows are not used in GLES3
  drivers/gles3/rasterizer_scene_gles3.cpp
  drivers/gles3/shaders/scene.glsl
Labels: bug, topic:rendering

#33864 Ensure move_and_slide() is consistent between the 2D and 3D versions.
  scene/2d/physics_body_2d.cpp
  scene/3d/physics_body.cpp
Labels: bug, needs testing, topic:physics

#34063 Tweak error timestamp formatting to be more readable
  editor/script_editor_debugger.cpp
Labels: enhancement, topic:editor

#33836 Fix Specular Blinn function
  drivers/gles2/shaders/scene.glsl
  drivers/gles3/shaders/scene.glsl
Labels: bug, topic:rendering

#33857 Fixed antialiased option for Polygon2D
  core/class_db.h
  doc/classes/Line2D.xml
  doc/classes/VisualServer.xml
  drivers/gles2/rasterizer_canvas_gles2.cpp
  drivers/gles2/rasterizer_canvas_gles2.h
  drivers/gles3/rasterizer_canvas_gles3.cpp
  drivers/gles3/rasterizer_canvas_gles3.h
  scene/2d/line_2d.cpp
  scene/2d/line_2d.h
  scene/2d/polygon_2d.cpp
  servers/visual/visual_server_canvas.cpp
  servers/visual/visual_server_canvas.h
  servers/visual/visual_server_raster.h
  servers/visual/visual_server_wrap_mt.h
  servers/visual_server.cpp
  servers/visual_server.h
Labels: bug, topic:rendering

#34061 Fix expressions for global constants in shaders
  servers/visual/shader_language.cpp
Labels: bug, topic:shaders

#34072 fixed pitch bend value and MIDI running status on the InputEventMIDI.
  core/os/midi_driver.cpp
  core/os/midi_driver.h
Labels: bug, enhancement, topic:audio, topic:input

#34074 Mention that `int()` can be used as an alternative to `floor()`
  modules/gdscript/doc_classes/@GDScript.xml
Labels: documentation, enhancement

#34075 Improve the Camera class documentation
  doc/classes/Camera.xml
Labels: documentation, enhancement

#34076 Add documentation for the Listener class
  doc/classes/Listener.xml
Labels: cherrypick:3.1, documentation, enhancement

#34077 Improve the DynamicFont class documentation
  doc/classes/DynamicFont.xml
Labels: cherrypick:3.1, documentation, enhancement

#34078 [iOS] Add export options to control external access to user data.
  misc/dist/ios_xcode/godot_ios/godot_ios-Info.plist
  platform/iphone/export/export.cpp
Labels: enhancement, platform:ios, topic:porting

#34082 Emscripten: Re-add BINARYEN_TRAP_MODE='clamp' for fastcomp
  platform/javascript/detect.py
Labels: bug, cherrypick:3.1, enhancement, topic:buildsystem

#34084 Fix severe performance drop while deflating polylines
  core/math/geometry.cpp
Labels: bug, topic:core

#34079 Don't stop export if rcedit path is invalid
  platform/windows/export/export.cpp
Labels: bug, topic:core

#34088 Properly orphan polygon index buffer after binding
  drivers/gles3/rasterizer_canvas_gles3.cpp
Labels: bug, topic:rendering

#34067 Make error when accidentially redeclaring a variable's type clearer
  modules/gdscript/gdscript_parser.cpp
Labels: enhancement, topic:gdscript

#34094 Fix compile error for Windows on Linux
  modules/camera/SCsub
Labels: bug, topic:buildsystem

#34087 OS class docs, adds platform compatibility notes.
  doc/classes/OS.xml
Labels: documentation, enhancement

#34096 Fixes translation for project sort options
  editor/project_manager.cpp
Labels: bug, topic:editor

#34097 Travis CI: Run `makerst.py` to check for documentation errors
  .travis.yml
  doc/tools/makerst.py
Labels: enhancement, topic:buildsystem

#33414 Added support for vertical syncing via the Windows OS compositor (DWM.)
  core/bind/core_bind.cpp
  core/bind/core_bind.h
  core/os/os.cpp
  core/os/os.h
  doc/classes/OS.xml
  doc/classes/ProjectSettings.xml
  main/main.cpp
  platform/windows/context_gl_windows.cpp
  platform/windows/context_gl_windows.h
  platform/windows/detect.py
  platform/windows/os_windows.cpp
Labels: bug, enhancement, platform:windows, topic:core, topic:rendering

#34099 Properly orphan polygon index buffer after binding (take 2)
  drivers/gles3/rasterizer_canvas_gles3.cpp
Labels: bug, topic:rendering

#34101 Mono/C#: Several android fixes
  modules/mono/build_scripts/mono_android_config.xml
  modules/mono/build_scripts/mono_configure.py
  modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs
  modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs
  modules/mono/editor/editor_internal_calls.cpp
  modules/mono/editor/godotsharp_export.cpp
  modules/mono/editor/godotsharp_export.h
  modules/mono/glue/Managed/Files/Array.cs
  modules/mono/glue/Managed/Files/Dictionary.cs
  modules/mono/glue/collections_glue.cpp
  modules/mono/glue/collections_glue.h
  modules/mono/mono_gd/gd_mono.cpp
  modules/mono/mono_gd/gd_mono_android.cpp
  modules/mono/mono_gd/gd_mono_android.h
  modules/mono/mono_gd/gd_mono_cache.h
  modules/mono/mono_gd/gd_mono_marshal.cpp
  thirdparty/misc/ifaddrs-android.h
Labels: bug, platform:android, topic:mono

#34039 Added Missing Binding for `multimesh_create` to VisualServer
  doc/classes/VisualServer.xml
  servers/visual_server.cpp
Labels: enhancement, topic:core

#34103 Translation: Use proper language code for locale near matching, including in ResourceLoader
  core/io/resource_loader.cpp
  core/translation.cpp
  core/translation.h
Labels: bug, cherrypick:3.1, topic:core

#34107 Fixes wrong position when adding node in VS editor
  modules/visual_script/visual_script_editor.cpp
Labels: bug, topic:editor, topic:visualscript

#34113 Fixes crash when clearing guides in empty scene
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor

#34018 Make sure to include the path in the "Data template directory not found" error message
  modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs
Labels: enhancement, topic:mono, usability

#34123 Fixed errors in JointSpatialGizmoPlugin when selecting a joint with unset nodes
  editor/spatial_editor_gizmos.cpp
Labels: bug, topic:editor

#34106 Don't store index of root nodes
  scene/resources/packed_scene.cpp
Labels: bug, topic:editor

#34114 changed set_meta to remove_meta in CLEAR_GUIDES menu option
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor

#34133 Call clear_meta when clearing guides with the ruler
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor

#34132 Docs: ARVRController and ARVRInterface
  doc/classes/ARVRController.xml
  doc/classes/ARVRInterface.xml
Labels: documentation, enhancement

#34128 doc: Fix and clarify AnimationPlayer play and stop descriptions
  doc/classes/AnimationPlayer.xml
Labels: cherrypick:3.1, documentation, enhancement

#34138 iOS: Disable armv7 as target arch by default
  platform/iphone/export/export.cpp
Labels: bug, platform:ios, topic:editor

#34142 Fix missing null checks in Mono Binding of GD
  modules/mono/glue/Managed/Files/GD.cs
Labels: bug, topic:mono

#34141 Remove extra spaces from parenthesis in *FileDialog's filter menu
  editor/editor_file_dialog.cpp
  scene/gui/file_dialog.cpp
Labels: enhancement, topic:core, topic:editor

#34155 Document RichTextEffect and CharFXTransform
  doc/classes/CharFXTransform.xml
  doc/classes/RichTextEffect.xml
Labels: documentation, enhancement

#34086 Improve the StyleBox class documentations
  doc/classes/StyleBoxFlat.xml
  doc/classes/StyleBoxLine.xml
  doc/classes/StyleBoxTexture.xml
Labels: documentation, enhancement

#34159 doc: Markup fixes for enums and constants
  doc/classes/AABB.xml
  doc/classes/ARVRPositionalTracker.xml
  doc/classes/Animation.xml
  doc/classes/AnimationTreePlayer.xml
  doc/classes/ArrayMesh.xml
  doc/classes/AudioStreamPlayer.xml
  doc/classes/AudioStreamSample.xml
  doc/classes/BaseButton.xml
  doc/classes/Button.xml
  doc/classes/Camera2D.xml
  doc/classes/CollisionPolygon2D.xml
  doc/classes/ConfigFile.xml
  doc/classes/CubeMap.xml
  doc/classes/Directory.xml
  doc/classes/EditorSettings.xml
  doc/classes/Environment.xml
  doc/classes/HTTPClient.xml
  doc/classes/HTTPRequest.xml
  doc/classes/IP.xml
  doc/classes/Image.xml
  doc/classes/ImmediateGeometry.xml
  doc/classes/Input.xml
  doc/classes/JSONParseResult.xml
  doc/classes/KinematicBody.xml
  doc/classes/Label.xml
  doc/classes/Light2D.xml
  doc/classes/Line2D.xml
  doc/classes/LineEdit.xml
  doc/classes/MultiplayerAPI.xml
  doc/classes/Particles.xml
  doc/classes/Particles2D.xml
  doc/classes/ParticlesMaterial.xml
  doc/classes/Physics2DServer.xml
  doc/classes/PhysicsServer.xml
  doc/classes/PrimitiveMesh.xml
  doc/classes/ProjectSettings.xml
  doc/classes/SceneTree.xml
  doc/classes/SurfaceTool.xml
  doc/classes/TabContainer.xml
  doc/classes/TextureButton.xml
  doc/classes/Theme.xml
  doc/classes/Tree.xml
  doc/classes/TreeItem.xml
  doc/classes/Tween.xml
  doc/classes/Variant.xml
  doc/classes/VisualServer.xml
  doc/classes/XMLParser.xml
  modules/gdscript/doc_classes/@GDScript.xml
  modules/visual_script/doc_classes/VisualScriptCustomNode.xml
  servers/visual_server.cpp
Labels: documentation, enhancement

#34160 Add a pre-commit hook to check the class reference syntax
  doc/tools/doc_merge.py
  doc/tools/doc_status.py
  misc/hooks/README.md
  misc/hooks/pre-commit
  misc/hooks/pre-commit-makerst
Labels: enhancement, topic:buildsystem

#34167 Add spaces after commas and strip extra ones in *FileDialog filter menu
  editor/editor_file_dialog.cpp
  scene/gui/file_dialog.cpp
Labels: enhancement, topic:core, topic:editor

#34188 Fix TilesetEditorContext snaps separation.
  editor/plugins/tile_set_editor_plugin.cpp
Labels: bug, cherrypick:3.1, topic:editor

#34202 [macOS] Send resize event without actually resizing window on backing change.
  platform/osx/os_osx.mm
Labels: bug, platform:osx, topic:porting

#34208 Fixed strange behaviour of scroll in the ItemList.
  scene/gui/item_list.cpp
Labels: bug, topic:core

#34203 Hide LineEdit placeholder if IME composition string is not empty.
  scene/gui/line_edit.cpp
Labels: bug, platform:osx, topic:porting

#34144 Fixes prompt closes the wrong scene on quit
  editor/editor_node.cpp
Labels: bug, topic:editor

#34163 Improve the PCKPacker class documentation
  doc/classes/PCKPacker.xml
Labels: documentation, enhancement

#34164 Make some arguments in PCKPacker methods optional
  core/io/pck_packer.cpp
  core/io/pck_packer.h
  doc/classes/PCKPacker.xml
Labels: enhancement, topic:core

#34210 Check that motion is not zero before doing a sweep test.
  modules/bullet/space_bullet.cpp
Labels: bug, topic:physics

#34218 GLES3: Properly unbind buffers after draw commands
  drivers/gles3/rasterizer_canvas_gles3.cpp
Labels: enhancement, topic:rendering

#34220 Document the KinematicBody axis lock methods
  doc/classes/KinematicBody.xml
Labels: documentation, enhancement

#34217 Fixes Delete Line doesn't delete first line in script
  editor/code_editor.cpp
  editor/code_editor.h
Labels: bug, topic:editor, usability

#34234 Update minimum size of SpinBox on theme change
  scene/gui/spin_box.cpp
Labels: bug, topic:core

#34040 Removed unused variables, add some constants numbers
  core/math/basis.cpp
  core/math/bsp_tree.cpp
  core/message_queue.cpp
  core/ustring.cpp
  editor/animation_track_editor.cpp
  editor/collada/collada.cpp
  editor/dependency_editor.cpp
  editor/editor_data.cpp
  editor/editor_folding.cpp
  editor/editor_node.cpp
  editor/editor_properties.cpp
  editor/export_template_manager.cpp
  editor/find_in_files.cpp
  editor/import/editor_import_collada.cpp
  editor/plugins/animation_player_editor_plugin.cpp
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/sprite_frames_editor_plugin.cpp
  editor/plugins/texture_region_editor_plugin.cpp
  editor/project_manager.cpp
  modules/assimp/editor_scene_importer_assimp.cpp
  modules/assimp/import_utils.h
  modules/gdnative/gdnative_library_editor_plugin.cpp
  modules/gdscript/language_server/gdscript_extend_parser.cpp
  modules/gdscript/language_server/gdscript_text_document.cpp
  modules/mbedtls/crypto_mbedtls.cpp
  modules/mbedtls/stream_peer_mbedtls.cpp
  modules/recast/navigation_mesh_generator.cpp
  modules/visual_script/visual_script_nodes.cpp
  scene/2d/collision_polygon_2d.cpp
  scene/2d/collision_shape_2d.cpp
  scene/2d/ray_cast_2d.cpp
  scene/3d/voxel_light_baker.cpp
  scene/animation/tween.h
  scene/gui/text_edit.cpp
  scene/gui/text_edit.h
  scene/main/scene_tree.cpp
  scene/resources/segment_shape_2d.cpp
  servers/physics/joints/cone_twist_joint_sw.cpp
  servers/physics/joints/hinge_joint_sw.cpp
  servers/physics_2d/physics_2d_server_sw.cpp
  servers/visual/shader_language.cpp
Labels: enhancement, topic:core

#34222 Improve the Shape/Shape2D classes documentation
  doc/classes/CollisionShape2D.xml
  doc/classes/Physics2DShapeQueryParameters.xml
  doc/classes/Physics2DShapeQueryResult.xml
  doc/classes/PhysicsShapeQueryParameters.xml
  doc/classes/PhysicsShapeQueryResult.xml
  doc/classes/PlaneShape.xml
  doc/classes/Shape.xml
  doc/classes/Shape2D.xml
Labels: documentation, enhancement

#34237 Force 32 bit depth buffer for WebGL
  drivers/gles2/rasterizer_storage_gles2.cpp
Labels: bug, topic:rendering

#34238 Use renderbuffer depth for post-process buffers when appropriate
  drivers/gles2/rasterizer_storage_gles2.cpp
Labels: bug, topic:rendering

#34250 Fix build on musl-based systems
  thirdparty/vhacd/0003-fix-musl-build.patch
  thirdparty/vhacd/inc/vhacdMutex.h
Labels: bug, platform:linuxbsd, topic:buildsystem

#34239 Fixes crash when using Theme::clear
  scene/resources/theme.cpp
Labels: bug, crash, topic:core

#34240 Fixes crash when shader inputs/outputs is invalid string
  scene/resources/visual_shader.cpp
Labels: bug, crash, topic:core

#34241 Fixes crash when using DynamicFont::set_font_data
  scene/resources/dynamic_font.cpp
Labels: bug, crash, topic:core

#34259 Fixes crash after set_piece_texture with invalid texture
  scene/resources/texture.cpp
Labels: bug, topic:core

#34261 Fixes infinite loop when switching editor
  editor/editor_node.cpp
Labels: bug, topic:editor

#34181 Support Rider as external editor for Godot mono version
  modules/mono/build_scripts/godot_tools_build.py
  modules/mono/editor/GodotTools/GodotTools/ExternalEditorId.cs
  modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs
  modules/mono/editor/GodotTools/GodotTools/GodotTools.csproj
  modules/mono/editor/GodotTools/GodotTools/Ides/GodotIdeManager.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/.editorconfig
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/RiderPathLocator.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/RiderPathManager.cs
  modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs
  modules/mono/editor/GodotTools/GodotTools/Utils/User32Dll.cs
  modules/mono/editor/GodotTools/GodotTools/packages.config
Labels: feature proposal, topic:editor, topic:mono

#33018 Fix `inst2dict` calling to getters to retrieve value
  modules/gdscript/gdscript_functions.cpp
Labels: bug, topic:gdscript

#34227 SCons: Add 'split_libmodules' option to workaround linker issue
  SConstruct
  drivers/SCsub
  methods.py
  modules/SCsub
  platform/windows/detect.py
Labels: bug, enhancement, topic:buildsystem

#34271 Disable GDScript warning for unused class variable by default
  modules/gdscript/gdscript.cpp
Labels: enhancement, topic:gdscript

#34274 Fix for #34186: "Center Selection" in 2D editor introduces graphic bias.
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor

#34282 Add note in 'load()' docs that the path must be absolute
  modules/gdscript/doc_classes/@GDScript.xml
Labels: documentation, enhancement

#27792 Fixes being unable to use the Quat(Vector3) constructor
  core/variant_call.cpp
Labels: bug, for pr meeting, topic:core

#34262 Add a default POINT_SIZE
  drivers/gles2/shader_compiler_gles2.cpp
  drivers/gles2/shaders/canvas.glsl
  drivers/gles2/shaders/scene.glsl
  drivers/gles3/shader_compiler_gles3.cpp
  drivers/gles3/shaders/canvas.glsl
  drivers/gles3/shaders/scene.glsl
Labels: bug, topic:rendering

#34251 Flip cull mode when rendering flipped Light2D and LightOccluder2D
  drivers/gles2/rasterizer_canvas_gles2.cpp
  drivers/gles3/rasterizer_canvas_gles3.cpp
Labels: bug, topic:rendering

#34283 Vertical scroll container margin is incorrect
  scene/gui/scroll_container.cpp
Labels: bug, topic:core

#34299 Added missed enum constant VisualShaderNodeTexture::SOURCE_PORT
  scene/resources/visual_shader_nodes.cpp
Labels: bug, topic:core

#34298 Fixes crash after remove_line in RichTextLabel
  scene/gui/rich_text_label.cpp
Labels: bug, crash, topic:core

#34277 Code formatting for the Mono module
  modules/mono/editor/GodotTools/GodotTools.BuildLogger/GodotBuildLogger.cs
  modules/mono/editor/GodotTools/GodotTools.BuildLogger/GodotTools.BuildLogger.csproj
  modules/mono/editor/GodotTools/GodotTools.Core/GodotTools.Core.csproj
  modules/mono/editor/GodotTools/GodotTools.Core/StringExtensions.cs
  modules/mono/editor/GodotTools/GodotTools.IdeConnection/GodotIdeClient.cs
  modules/mono/editor/GodotTools/GodotTools.IdeConnection/GodotIdeConnection.cs
  modules/mono/editor/GodotTools/GodotTools.IdeConnection/GodotTools.IdeConnection.csproj
  modules/mono/editor/GodotTools/GodotTools.IdeConnection/MessageComposer.cs
  modules/mono/editor/GodotTools/GodotTools.IdeConnection/MessageParser.cs
  modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs
  modules/mono/editor/GodotTools/GodotTools.ProjectEditor/packages.config
  modules/mono/editor/GodotTools/GodotTools/BottomPanel.cs
  modules/mono/editor/GodotTools/GodotTools/Build/BuildSystem.cs
  modules/mono/editor/GodotTools/GodotTools/Build/MsBuildFinder.cs
  modules/mono/editor/GodotTools/GodotTools/BuildManager.cs
  modules/mono/editor/GodotTools/GodotTools/BuildTab.cs
  modules/mono/editor/GodotTools/GodotTools/CsProjOperations.cs
  modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs
  modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs
  modules/mono/editor/GodotTools/GodotTools/GodotTools.csproj
  modules/mono/editor/GodotTools/GodotTools/HotReloadAssemblyWatcher.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/GodotIdeManager.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/GodotIdeServer.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/.editorconfig
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/RiderPathLocator.cs
  modules/mono/editor/GodotTools/GodotTools/Ides/Rider/RiderPathManager.cs
  modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs
  modules/mono/editor/GodotTools/GodotTools/Internals/ScriptClassParser.cs
  modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs
  modules/mono/editor/GodotTools/GodotTools/packages.config
  modules/mono/glue/Managed/Managed.csproj
Labels: enhancement, topic:mono

#34286 Fix GDScript autocompletion with "as" or typed variables
  modules/gdscript/gdscript_editor.cpp
Labels: bug, topic:editor, topic:gdscript

#34307 [Vulkan] Restore parts of #33783 and #32809 missing after rebase.
  .travis.yml
  platform/osx/context_gl_osx.h
  platform/osx/context_gl_osx.mm
  platform/osx/os_osx.mm
Labels: bug, platform:osx, topic:porting

#34306 Fixed an issue with recording audio.
  servers/audio/effects/audio_effect_record.cpp
Labels: bug, topic:audio

#34309 Fixed HTTPClient.xml:115 and 121 variant declaration
  doc/classes/HTTPClient.xml
Labels: bug, documentation

#34314 Make Button and co. take internal margins into account when clipping text
  scene/gui/button.cpp
Labels: bug, topic:core

#34315 Fix OptionButton's arrow margin in editor theme
  editor/editor_themes.cpp
Labels: bug, topic:editor

#34295 [Mono] Fix string Find methods having reversed case sensitivity
  modules/mono/glue/Managed/Files/StringExtensions.cs
Labels: bug, topic:mono

#34304 Don't search in unassigned shortcut labels in the editor shortcuts
  editor/settings_config_dialog.cpp
Labels: enhancement, topic:editor, usability

#34016 Fix TileSet Editor polygon point grabbing
  editor/plugins/tile_set_editor_plugin.cpp
  editor/plugins/tile_set_editor_plugin.h
Labels: bug, topic:editor, usability

#34189 Expose Mesh get_aabb
  doc/classes/Mesh.xml
  scene/resources/mesh.cpp
Labels: enhancement, topic:core

#34235 Fixes long popup menu scroll behavior
  scene/gui/popup_menu.cpp
Labels: bug, platform:osx, topic:core, topic:editor

#34323 Make more editor strings translatable
  editor/export_template_manager.cpp
  editor/plugins/asset_library_editor_plugin.cpp
  editor/project_export.cpp
Labels: enhancement, topic:editor

#34287 Provide default Tween values for transition and easing types
  scene/animation/tween.cpp
  scene/animation/tween.h
Labels: enhancement, topic:core

#34310 Don't allow to use too big or too small shift count
  core/variant_op.cpp
Labels: bug, topic:core

#34229 Allow to change the home indicator behaviour on iOS
  doc/classes/ProjectSettings.xml
  main/main.cpp
  platform/iphone/view_controller.h
  platform/iphone/view_controller.mm
Labels: bug, platform:ios, topic:porting

#34328 Clarifying how float(String from) parses partially invalid strings
  doc/classes/float.xml
Labels: documentation, enhancement

#34331 vhacd: Patch to fix UWP ARM build
  thirdparty/vhacd/0004-fix-uwp-arm-build.patch
  thirdparty/vhacd/inc/btScalar.h
Labels: bug, platform:uwp, topic:thirdparty

#34327 Makes int and bool types clickable in documentation
  editor/editor_help.cpp
Labels: enhancement, topic:editor

#34333 Fix some cases where typed assignment gets invalid
  modules/gdscript/gdscript.cpp
  modules/gdscript/gdscript_compiler.cpp
  modules/gdscript/gdscript_function.cpp
  modules/gdscript/gdscript_parser.cpp
Labels: bug, cherrypick:3.1, topic:gdscript

#34334 Mono/C#: Fix class parser bug with 'where T : struct'
  modules/mono/editor/script_class_parser.cpp
Labels: bug, topic:editor, topic:mono

#34293 Fix for collision polygon not working at all on exported builds.
  scene/3d/collision_polygon.cpp
Labels: bug, topic:physics

#34340 Drop b2d_convexdecomp, no longer necessary.
  COPYRIGHT.txt
  core/math/geometry.cpp
  core/math/geometry.h
  drivers/convex_decomp/SCsub
  drivers/convex_decomp/b2d_decompose.cpp
  drivers/convex_decomp/b2d_decompose.h
  drivers/register_driver_types.cpp
  thirdparty/README.md
  thirdparty/b2d_convexdecomp/b2Glue.h
  thirdparty/b2d_convexdecomp/b2Polygon.cpp
  thirdparty/b2d_convexdecomp/b2Polygon.h
  thirdparty/b2d_convexdecomp/b2Triangle.cpp
  thirdparty/b2d_convexdecomp/b2Triangle.h
Labels: enhancement, topic:thirdparty

#34339 Change bundle name rules on iOS to match Apple's requirements
  platform/iphone/export/export.cpp
Labels: enhancement, platform:ios, topic:editor

#34338 Fixed an issue with capturing audio from microphones in macOS.
  misc/dist/osx_template.app/Contents/Info.plist
  misc/dist/osx_tools.app/Contents/Info.plist
  platform/osx/export/export.cpp
Labels: bug, platform:osx, topic:audio, topic:porting

#34350 Remove convex_decomp in drivers/SCsub
  drivers/SCsub
Labels: enhancement, topic:buildsystem

#34300 Added apply_impulse methods to PhysicalBone for ragdolls
  scene/3d/physics_body.cpp
  scene/3d/physics_body.h
Labels: enhancement, topic:physics

#34272 Fix for #34258 and added get_zoom_hbox() documentation.
  doc/classes/GraphEdit.xml
Labels: enhancement, topic:core

#34353 Increase the TileSet and polygon UV editor zoom limits to 16×
  editor/plugins/polygon_2d_editor_plugin.cpp
  editor/plugins/tile_set_editor_plugin.cpp
Labels: enhancement, topic:editor, usability

#34361 Fixes wrong minimum size of Group Editor
  editor/groups_editor.cpp
Labels: bug, topic:editor

#34344 Remove unused theme elements in H/VSlider
  scene/gui/slider.cpp
  scene/resources/default_theme/default_theme.cpp
Labels: bug, topic:core

#34356 Lower the maximum StyleBoxFlat corner detail to 20
  scene/resources/style_box.cpp
Labels: bug, topic:gui

#34360 Updates docs for GDScript built-in functions
  modules/gdscript/doc_classes/@GDScript.xml
  modules/gdscript/gdscript_functions.cpp
Labels: documentation, enhancement

#34336 Document that translated does not behave like rotated or scaled
  core/variant_call.cpp
  doc/classes/Transform.xml
  doc/classes/Transform2D.xml
Labels: documentation, enhancement

#34367 Fix shadow color in GLES2 by making sRGB
  drivers/gles2/rasterizer_scene_gles2.cpp
Labels: bug, topic:rendering

#34374 Prevent infinite loop when focus_next is invisible
  scene/gui/control.cpp
Labels: bug, topic:gui

#34372 Mention how to add slots to GraphNode
  doc/classes/GraphNode.xml
Labels: documentation, enhancement, topic:gui

#34375 Center error icon vertically in AssetLib
  editor/plugins/asset_library_editor_plugin.cpp
Labels: bug, topic:assetlib

#34311 Fix- using cut in first line of a script file does not remove the line
  scene/gui/text_edit.cpp
Labels: bug, topic:core

#34280 Fix documentation for yield
  modules/gdscript/doc_classes/@GDScript.xml
Labels: bug, documentation

#34377 Makes more strings in editor translatable
  editor/editor_feature_profile.cpp
  editor/editor_node.cpp
  editor/plugins/canvas_item_editor_plugin.cpp
  editor/plugins/theme_editor_plugin.cpp
  editor/project_export.cpp
  editor/project_manager.cpp
  modules/visual_script/visual_script_editor.cpp
Labels: enhancement, topic:editor

#34269 Scroll ScrollContainer to focused children
  doc/classes/Viewport.xml
  scene/gui/scroll_container.cpp
  scene/gui/scroll_container.h
  scene/main/viewport.cpp
Labels: bug, topic:core

#34246 Fixed a bug within sprite.cpp that caused a nan value to appear
  scene/2d/sprite.cpp
Labels: bug, topic:core

#34380 Mono: Enable threads suspend workaround on Windows
  modules/mono/mono_gd/gd_mono.cpp
Labels: bug, cherrypick:3.1, platform:windows, topic:mono

#34382 Allow attaching any external profiler, including JetBrains dotTrace
  modules/mono/mono_gd/gd_mono.cpp
Labels: enhancement, topic:mono

#34389 Use global transform when calculating scroll
  scene/gui/scroll_container.cpp
Labels: bug, regression, topic:gui

#34391 Fixes size of Create Function dialog
  modules/visual_script/visual_script_editor.cpp
Labels: bug, topic:editor

#34364 Moves switch for show scripts panel from File menu to status bar
  editor/code_editor.cpp
  editor/code_editor.h
  editor/plugins/script_editor_plugin.cpp
  editor/plugins/script_editor_plugin.h
Labels: enhancement, topic:editor

#34393 Prevent showing toggle scripts panel switch in shader editor
  editor/code_editor.cpp
  editor/code_editor.h
  editor/plugins/script_text_editor.cpp
Labels: bug, topic:editor

#34397 Mono/C#: Fix project export and fix FindLast/GetFile regression
  modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs
  modules/mono/glue/Managed/Files/StringExtensions.cs
Labels: bug, topic:mono

#34401 Fix crash on Android with no manifest permissions.
  platform/android/java/lib/src/org/godotengine/godot/utils/PermissionsUtil.java
Labels: bug, crash, high priority, platform:android, regression

#34402 Fix toggle scripts panel to allow using shortcut in other areas
  editor/code_editor.cpp
  editor/code_editor.h
  editor/plugins/script_editor_plugin.cpp
  editor/plugins/script_editor_plugin.h
  editor/plugins/script_text_editor.h
Labels: bug, topic:editor

#34407 Improve the `KEY_MASK_CMD` documentation
  doc/classes/@GlobalScope.xml
Labels: documentation, enhancement

#34406 Make NetSockets quieter.
  drivers/unix/net_socket_posix.cpp
  drivers/unix/net_socket_posix.h
Labels: enhancement, topic:network

#34348 Fixed issues with using a relative path in the export window.
  core/ustring.cpp
  editor/editor_file_dialog.cpp
Labels: bug, topic:editor

#34412 Docs: OptionButton
  doc/classes/OptionButton.xml
Labels: documentation, enhancement

#34418 Updates docs of AABB and Plane
  doc/classes/AABB.xml
  doc/classes/Plane.xml
Labels: documentation, enhancement

#34417 Make right align for calls number in Profiler
  editor/editor_profiler.cpp
Labels: enhancement, topic:editor, usability

#34423 Updates toggle scripts switch tooltip (if user changed the shortcut)
  editor/code_editor.cpp
Labels: bug, topic:editor

#34419 Mono: Copy native and btls libs on macOS
  modules/mono/build_scripts/mono_configure.py
Labels: bug, platform:osx, topic:buildsystem, topic:mono

#34430 Fix error log when selecting child of Containers
  editor/plugins/canvas_item_editor_plugin.cpp
Labels: bug, topic:editor

#34450 Fixes Curve Editor margin
  editor/plugins/curve_editor_plugin.cpp
Labels: bug, topic:editor

#34437 Fix ScriptTextEditor encapsulation
  editor/code_editor.cpp
  editor/plugins/script_editor_plugin.cpp
  editor/plugins/script_editor_plugin.h
  editor/plugins/script_text_editor.cpp
  editor/plugins/script_text_editor.h
Labels: bug, topic:core
